env:
  browser: true
  es6: true
  commonjs: true
  node: true
  jest: true
settings:
  react:
    version: 'detect'
parser: '@typescript-eslint/parser'
plugins:
  - 'jest'
  - 'react'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/react'
  - 'prettier/@typescript-eslint'
rules:
  no-var: error
  prefer-const: error
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      react/prop-types: off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/no-empty-interface': off
