env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: 'module'
plugins:
  - 'react'
  - 'jest'
overrides:
  - files:
      - '**/*.test.*' # Remove no-undef rule from jest files.
    rules:
      no-undef: off
rules:
  react/prop-types: off
  no-unused-vars: off
